spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"

gigglegazette:
  app:
    jwtSecret: ======================ProjectGiggleGazette=Spring===========================
    jwtExpirationMs: 86400000