server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: article-service-articles
          uri: lb://article-service
          predicates:
            - Path=/articles/**
        - id: article-service-categories
          uri: lb://article-service
          predicates:
            - Path=/categories/**
        - id: article-service-comments
          uri: lb://article-service
          predicates:
            - Path=/comments/**
        - id: article-service-images
          uri: lb://article-service
          predicates:
            - Path=/images/**
        - id: article-service-subcategory
          uri: lb://article-service
          predicates:
            - Path=/subcategories/**

        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: user-service-roles
          uri: lb://user-service
          predicates:
            - Path=/roles/**
        - id: user-service-profiles
          uri: lb://user-service
          predicates:
            - Path=/profiles/**
        - id: user-service-permissions
          uri: lb://user-service
          predicates:
            - Path=/permissions/**
